copy_config_files:
	./copy-config-files.sh

apply_aais_secrets:
	node apply-secrets.js aais
	
apply_analytics_secrets:
	node apply-secrets.js analytics
	
apply_carrier_secrets:
	node apply-secrets.js carrier
	
copy_aais_secrets:
	./copy-config-files.sh
	node apply-secrets.js aais

copy_analytics_secrets:
	./copy-config-files.sh
	node apply-secrets.js analytics

copy_carrier_secrets:
	./copy-config-files.sh
	node apply-secrets.js carrier


