{{- if .Values.global.etl.install }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi
  namespace: nifi
spec:
  serviceName: nifi
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      dnsConfig:
        searches: ['nifi.nifi.svc.cluster.local']
      volumes:
      - name: apkey
        secret:
          secretName: {{ .Values.global.appsecret }}
      containers:
      - name: nifi-container
        image: openidl/data-etl:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.global.etl.port }}
          name: http
        - containerPort: 9088
          name: node-pp
        - containerPort: 8888
          name: s2s
        env:
        - name: VERSION
          value: "1.9.2"
        - name: NIFI_CLUSTER_IS_NODE
          value: "true"
        - name: NIFI_CLUSTER_NODE_PROTOCOL_PORT
          value: "9088"
        - name: NIFI_ELECTION_MAX_CANDIDATES
          value: "1"
        - name: NIFI_ZK_CONNECT_STRING
          value: "zk-0.zk-hs.nifi.svc.cluster.local:2181,zk-1.zk-hs.nifi.svc.cluster.local:2181,zk-2.zk-hs.nifi.svc.cluster.local:2181"
        volumeMounts:
        {{- range .Values.secrets }}
        - name: apkey
          mountPath: /server/config/{{ .file }}
          subPath: {{ .name }}
        {{- end }}
{{- end }}
